import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-between min-h-screen w-11/12 mx-auto"
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <h2 className="text-4xl">Navigation</h2>
        </div>
        <div>
          {children}
        </div>
        <div>
          <h2 className="text-2xl">Footer</h2>
        </div>
      </body>
    </html>
  );
}
